name: .Net Core CI

on:
  
  pull_request:
    branches: [ main, staging ]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-2019]
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - name: Build with dotnet
      run: dotnet build com.movistar.ratemovies.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test com.movistar.ratemovies.sln --configuration Release
